--
-- PostgreSQL database cluster dump
--

SET default_transaction_read_only = off;

SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

--
-- Roles
--

CREATE ROLE nstoykov;
ALTER ROLE nstoykov WITH SUPERUSER INHERIT NOCREATEROLE CREATEDB LOGIN NOREPLICATION NOBYPASSRLS PASSWORD 'SCRAM-SHA-256$4096:oHBe7eZSWJhgRAZaLRj/XA==$l53Il8ZhrzMzJHNwxz0CEJYOsFUzMaQ/1huSfxe8Z2M=:wIGtwK7vkxTfywGNk0se6M30BWDcJlgNb5hDHwmpJok=';
CREATE ROLE postgres;
ALTER ROLE postgres WITH SUPERUSER INHERIT CREATEROLE CREATEDB LOGIN REPLICATION BYPASSRLS PASSWORD 'SCRAM-SHA-256$4096:nY6auK8Bd5B4riULnuRo8Q==$PArLvNYu6vp0PBjeurnp7X6YJR+dmkKLiqQzPB6hRVg=:ip3Vxrvd1GvhlgqTolmIVa3J/SwPjH6Sk3P7rCCDMNU=';

--
-- User Configurations
--

--
-- User Config "nstoykov"
--

ALTER ROLE nstoykov SET client_encoding TO 'utf8';
ALTER ROLE nstoykov SET default_transaction_isolation TO 'read committed';
ALTER ROLE nstoykov SET "TimeZone" TO 'UTC';








--
-- Databases
--

--
-- Database "template1" dump
--

\connect template1

--
-- PostgreSQL database dump
--

-- Dumped from database version 17rc1
-- Dumped by pg_dump version 17rc1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- PostgreSQL database dump complete
--

--
-- Database "cinebase" dump
--

--
-- PostgreSQL database dump
--

-- Dumped from database version 17rc1
-- Dumped by pg_dump version 17rc1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: cinebase; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE cinebase WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'Bulgarian_Bulgaria.1251';


ALTER DATABASE cinebase OWNER TO postgres;

\connect cinebase

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: nstoykov
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO nstoykov;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: nstoykov
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: nstoykov
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO nstoykov;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: nstoykov
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: nstoykov
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO nstoykov;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: nstoykov
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: nstoykov
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO nstoykov;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: nstoykov
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO nstoykov;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: nstoykov
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: nstoykov
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: nstoykov
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO nstoykov;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: nstoykov
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authtoken_token; Type: TABLE; Schema: public; Owner: nstoykov
--

CREATE TABLE public.authtoken_token (
    key character varying(40) NOT NULL,
    created timestamp with time zone NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.authtoken_token OWNER TO nstoykov;

--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: nstoykov
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO nstoykov;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: nstoykov
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: nstoykov
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO nstoykov;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: nstoykov
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: nstoykov
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO nstoykov;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: nstoykov
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: nstoykov
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO nstoykov;

--
-- Name: media_app_media; Type: TABLE; Schema: public; Owner: nstoykov
--

CREATE TABLE public.media_app_media (
    id bigint NOT NULL,
    title character varying(50) NOT NULL,
    storyline character varying(200) NOT NULL,
    active boolean NOT NULL,
    avg_rating double precision,
    created timestamp with time zone NOT NULL,
    streaming_platform_id bigint NOT NULL,
    user_rating integer NOT NULL
);


ALTER TABLE public.media_app_media OWNER TO nstoykov;

--
-- Name: media_app_media_id_seq; Type: SEQUENCE; Schema: public; Owner: nstoykov
--

ALTER TABLE public.media_app_media ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.media_app_media_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: media_app_review; Type: TABLE; Schema: public; Owner: nstoykov
--

CREATE TABLE public.media_app_review (
    id bigint NOT NULL,
    rating integer NOT NULL,
    description character varying(200) NOT NULL,
    active boolean NOT NULL,
    created timestamp with time zone NOT NULL,
    update timestamp with time zone NOT NULL,
    media_id bigint NOT NULL,
    reviewer_id integer NOT NULL,
    CONSTRAINT media_app_review_rating_check CHECK ((rating >= 0))
);


ALTER TABLE public.media_app_review OWNER TO nstoykov;

--
-- Name: media_app_review_id_seq; Type: SEQUENCE; Schema: public; Owner: nstoykov
--

ALTER TABLE public.media_app_review ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.media_app_review_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: media_app_streamingplatform; Type: TABLE; Schema: public; Owner: nstoykov
--

CREATE TABLE public.media_app_streamingplatform (
    id bigint NOT NULL,
    name character varying(30) NOT NULL,
    about character varying(150) NOT NULL,
    website character varying(100) NOT NULL
);


ALTER TABLE public.media_app_streamingplatform OWNER TO nstoykov;

--
-- Name: media_app_streamingplatform_id_seq; Type: SEQUENCE; Schema: public; Owner: nstoykov
--

ALTER TABLE public.media_app_streamingplatform ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.media_app_streamingplatform_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: nstoykov
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: nstoykov
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: nstoykov
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add streaming platform	1	add_streamingplatform
2	Can change streaming platform	1	change_streamingplatform
3	Can delete streaming platform	1	delete_streamingplatform
4	Can view streaming platform	1	view_streamingplatform
5	Can add media	2	add_media
6	Can change media	2	change_media
7	Can delete media	2	delete_media
8	Can view media	2	view_media
9	Can add review	3	add_review
10	Can change review	3	change_review
11	Can delete review	3	delete_review
12	Can view review	3	view_review
13	Can add log entry	4	add_logentry
14	Can change log entry	4	change_logentry
15	Can delete log entry	4	delete_logentry
16	Can view log entry	4	view_logentry
17	Can add permission	5	add_permission
18	Can change permission	5	change_permission
19	Can delete permission	5	delete_permission
20	Can view permission	5	view_permission
21	Can add group	6	add_group
22	Can change group	6	change_group
23	Can delete group	6	delete_group
24	Can view group	6	view_group
25	Can add user	7	add_user
26	Can change user	7	change_user
27	Can delete user	7	delete_user
28	Can view user	7	view_user
29	Can add content type	8	add_contenttype
30	Can change content type	8	change_contenttype
31	Can delete content type	8	delete_contenttype
32	Can view content type	8	view_contenttype
33	Can add session	9	add_session
34	Can change session	9	change_session
35	Can delete session	9	delete_session
36	Can view session	9	view_session
37	Can add Token	10	add_token
38	Can change Token	10	change_token
39	Can delete Token	10	delete_token
40	Can view Token	10	view_token
41	Can add Token	11	add_tokenproxy
42	Can change Token	11	change_tokenproxy
43	Can delete Token	11	delete_tokenproxy
44	Can view Token	11	view_tokenproxy
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: nstoykov
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
2	nstoykov	\N	f	nstoykov_0				f	t	2024-09-13 06:49:07.772872+00
3	nstoykov	\N	f	nstoykov_1				f	t	2024-09-13 06:49:07.775864+00
4	nstoykov	\N	f	nstoykov_2				f	t	2024-09-13 06:49:07.776879+00
5	nstoykov	\N	f	nstoykov_3				f	t	2024-09-13 06:49:07.777843+00
6	nstoykov	\N	f	nstoykov_4				f	t	2024-09-13 06:49:07.779875+00
7	nstoykov	\N	f	nstoykov_5				f	t	2024-09-13 06:49:07.78088+00
8	nstoykov	\N	f	nstoykov_6				f	t	2024-09-13 06:49:07.781873+00
9	nstoykov	\N	f	nstoykov_7				f	t	2024-09-13 06:49:07.782872+00
10	nstoykov	\N	f	nstoykov_8				f	t	2024-09-13 06:49:07.783856+00
11	nstoykov	\N	f	nstoykov_9				f	t	2024-09-13 06:49:07.784846+00
12	nstoykov	\N	f	nstoykov_10				f	t	2024-09-13 06:49:07.786861+00
13	nstoykov	\N	f	nstoykov_11				f	t	2024-09-13 06:49:07.788843+00
14	nstoykov	\N	f	nstoykov_12				f	t	2024-09-13 06:49:07.789874+00
15	nstoykov	\N	f	nstoykov_13				f	t	2024-09-13 06:49:07.790861+00
16	nstoykov	\N	f	nstoykov_14				f	t	2024-09-13 06:49:07.791874+00
17	nstoykov	\N	f	nstoykov_15				f	t	2024-09-13 06:49:07.792873+00
18	nstoykov	\N	f	nstoykov_16				f	t	2024-09-13 06:49:07.793872+00
19	nstoykov	\N	f	nstoykov_17				f	t	2024-09-13 06:49:07.793872+00
20	nstoykov	\N	f	nstoykov_18				f	t	2024-09-13 06:49:07.795883+00
21	nstoykov	\N	f	nstoykov_19				f	t	2024-09-13 06:49:07.796883+00
22	nstoykov	\N	f	nstoykov_20				f	t	2024-09-13 06:49:07.79788+00
23	nstoykov	\N	f	nstoykov_21				f	t	2024-09-13 06:49:07.799856+00
24	nstoykov	\N	f	nstoykov_22				f	t	2024-09-13 06:49:07.800847+00
25	nstoykov	\N	f	nstoykov_23				f	t	2024-09-13 06:49:07.802845+00
26	nstoykov	\N	f	nstoykov_24				f	t	2024-09-13 06:49:07.803844+00
27	nstoykov	\N	f	nstoykov_25				f	t	2024-09-13 06:49:07.805855+00
28	nstoykov	\N	f	nstoykov_26				f	t	2024-09-13 06:49:07.80687+00
29	nstoykov	\N	f	nstoykov_27				f	t	2024-09-13 06:49:07.807873+00
30	nstoykov	\N	f	nstoykov_28				f	t	2024-09-13 06:49:07.807873+00
31	nstoykov	\N	f	nstoykov_29				f	t	2024-09-13 06:49:07.80887+00
32	nstoykov	\N	f	nstoykov_30				f	t	2024-09-13 06:49:07.809874+00
33	nstoykov	\N	f	nstoykov_31				f	t	2024-09-13 06:49:07.811874+00
34	nstoykov	\N	f	nstoykov_32				f	t	2024-09-13 06:49:07.812876+00
35	nstoykov	\N	f	nstoykov_33				f	t	2024-09-13 06:49:07.813874+00
36	nstoykov	\N	f	nstoykov_34				f	t	2024-09-13 06:49:07.814872+00
37	nstoykov	\N	f	nstoykov_35				f	t	2024-09-13 06:49:07.816856+00
38	nstoykov	\N	f	nstoykov_36				f	t	2024-09-13 06:49:07.817845+00
39	nstoykov	\N	f	nstoykov_37				f	t	2024-09-13 06:49:07.819869+00
40	nstoykov	\N	f	nstoykov_38				f	t	2024-09-13 06:49:07.821853+00
41	nstoykov	\N	f	nstoykov_39				f	t	2024-09-13 06:49:07.822853+00
42	nstoykov	\N	f	nstoykov_40				f	t	2024-09-13 06:49:07.822853+00
43	nstoykov	\N	f	nstoykov_41				f	t	2024-09-13 06:49:07.824843+00
44	nstoykov	\N	f	nstoykov_42				f	t	2024-09-13 06:49:07.825845+00
45	nstoykov	\N	f	nstoykov_43				f	t	2024-09-13 06:49:07.827873+00
46	nstoykov	\N	f	nstoykov_44				f	t	2024-09-13 06:49:07.828876+00
47	nstoykov	\N	f	nstoykov_45				f	t	2024-09-13 06:49:07.829884+00
48	nstoykov	\N	f	nstoykov_46				f	t	2024-09-13 06:49:07.831882+00
49	nstoykov	\N	f	nstoykov_47				f	t	2024-09-13 06:49:07.832871+00
50	nstoykov	\N	f	nstoykov_48				f	t	2024-09-13 06:49:07.833876+00
51	nstoykov	\N	f	nstoykov_49				f	t	2024-09-13 06:49:07.835844+00
52	nstoykov	\N	f	nstoykov_50				f	t	2024-09-13 06:49:07.836876+00
1	pbkdf2_sha256$870000$YfLl7geXrutBXvUXExPcoQ$g6ZzyqE8a864wt2JgcnPAlatZ5FYm/xZiWM2SpvTX4Q=	2024-09-13 06:49:26.003845+00	t	nstoykov_admin			example@example.com	t	t	2024-09-13 06:48:35.854865+00
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: nstoykov
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: nstoykov
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: authtoken_token; Type: TABLE DATA; Schema: public; Owner: nstoykov
--

COPY public.authtoken_token (key, created, user_id) FROM stdin;
f3b4c6f7ad4925e9e426d9c66240f3cac044967e	2024-09-13 06:48:36.186863+00	1
3f315eb0b4809890e26d5be73c07ca4cc8894d00	2024-09-13 06:49:07.773853+00	2
51db5aa3691f1d6d7897b8eaa1db87ad6dda0ddb	2024-09-13 06:49:07.776879+00	3
f68b6ef626a8d2a71413496513b83edc273c271f	2024-09-13 06:49:07.777843+00	4
f3085321bd76ca98775eaa2c849012374cc36a0b	2024-09-13 06:49:07.778877+00	5
667dab89607740c5ff8d7e724fba8a6fbbb9774e	2024-09-13 06:49:07.779875+00	6
30e338959a4832571b74394ebddc262305abc100	2024-09-13 06:49:07.78088+00	7
be2a0832e3a1de286278b0de4f00bc725900c9ce	2024-09-13 06:49:07.781873+00	8
115020c8e07d541ceb531e2e1b90da7aa04d7d54	2024-09-13 06:49:07.783856+00	9
24d6d963271155e45987ec379096998b9b326835	2024-09-13 06:49:07.784846+00	10
9991a6455b7298062500ad61bb284f0a8f3c20f9	2024-09-13 06:49:07.786861+00	11
6fed58846cdee50b89ad7a8bb3547693d98bd31b	2024-09-13 06:49:07.787845+00	12
24379ed00d199831d3c89faad7d503f8df9b1031	2024-09-13 06:49:07.788843+00	13
eb86dba56dcc9584b84c3869e4a9635b7ad6e23e	2024-09-13 06:49:07.789874+00	14
808464773288f13658718dfa9d3fe8613c8fc388	2024-09-13 06:49:07.791874+00	15
8ec48f55c6a37ff7c6983393a1668271fd0972e9	2024-09-13 06:49:07.791874+00	16
cc091e92717431e702375b636af379057b629720	2024-09-13 06:49:07.792873+00	17
1fb95b86aabe20ef09f90a6ab3658d97d9e181eb	2024-09-13 06:49:07.793872+00	18
3ae841260893ca263fa302e2e1cef9ccaa28691f	2024-09-13 06:49:07.795883+00	19
2be12f9bad3b03155baff3c95f24e93b6e8876c1	2024-09-13 06:49:07.796883+00	20
6177a69fbd7ecbb2458cdef01cd300d86896d488	2024-09-13 06:49:07.79788+00	21
b4d442c5d2c1b8da1b284d240ca327b5c344755d	2024-09-13 06:49:07.79887+00	22
1294514d5a0669e895fc06dae3cd7287ca4e6145	2024-09-13 06:49:07.799856+00	23
52db9d93b851ff7ca7a47f05f62738b2d08daec2	2024-09-13 06:49:07.801857+00	24
d987d9082a08647078414ffc0908029705b78b06	2024-09-13 06:49:07.803844+00	25
35dd3611f72b58744cd4ad9c95c2698fb3eed842	2024-09-13 06:49:07.804855+00	26
6d693336c2a20798cf39892f7a38c8aee020a9b3	2024-09-13 06:49:07.805855+00	27
8c51e5ceb81ef95609220edfd51147e0f3357c9e	2024-09-13 06:49:07.80687+00	28
c3eabe902fb420a33fead17dd83494c75ea946fb	2024-09-13 06:49:07.807873+00	29
7404e56f6bd8ded216b619b739d51c206b7cc576	2024-09-13 06:49:07.80887+00	30
84be8a83bc34d6e6a0437e615b8f5ea5ccf799ac	2024-09-13 06:49:07.809874+00	31
db894e16f8cec7db9d7e3dcd68b86b56940b346a	2024-09-13 06:49:07.810861+00	32
00842c601223fcc0f3075be948c4f74ea6a17715	2024-09-13 06:49:07.812876+00	33
719d37db78cb4b6fcf1ace0f50bdcdcc8245d4b5	2024-09-13 06:49:07.813874+00	34
8d2223c484a5c1c0557c6b3904f17cfe28cf11f7	2024-09-13 06:49:07.814872+00	35
50002b4da0234625ff9e010bb7454a5a12839be4	2024-09-13 06:49:07.815872+00	36
bdb9f906c28257f817afdd3b5c3c62da1b8bca5b	2024-09-13 06:49:07.817845+00	37
2bdc7c9a0363ef4eb32e7bc01d7964ea6c013a72	2024-09-13 06:49:07.819869+00	38
f1c6ba228cdae1b14f2b0dec2781274e54e394f8	2024-09-13 06:49:07.820844+00	39
d54d2fcdab020a6a4f657c1f6bc3a74feba77184	2024-09-13 06:49:07.821853+00	40
7c000938c4b068fe12d464d1717ef968d40bb5e2	2024-09-13 06:49:07.822853+00	41
7dd2f03e331417bd181f7aa5c6f4502faac09443	2024-09-13 06:49:07.823877+00	42
58faa0e6384ec3cda40109a7fb92c30225648232	2024-09-13 06:49:07.825845+00	43
3c3ee42773fa3fe86f0e58a66765ca92ea794e23	2024-09-13 06:49:07.826857+00	44
3fb2090d01c2530ce45adae190735dbfe539ca01	2024-09-13 06:49:07.828876+00	45
de156b28ab3f4f4a765a0412f6fccb6e672b72c2	2024-09-13 06:49:07.829884+00	46
adf1997f809ec8ef99c889d525f9e21bc35e729a	2024-09-13 06:49:07.830855+00	47
6f44e38b32f177b6653cdc3ebb4cdbf7e039eb44	2024-09-13 06:49:07.832871+00	48
ddf6e866e479eb5ab5a98dab59d08c691c7063e3	2024-09-13 06:49:07.832871+00	49
8fa144e6e3509b2f23f604f0dfc3235ac4efc50d	2024-09-13 06:49:07.834856+00	50
f479d8985687c4275709b08ed210f14f92b2c5e1	2024-09-13 06:49:07.836876+00	51
3e539e5dc8de96280e9d4f2d510a2e7f1b0b9ba0	2024-09-13 06:49:07.837873+00	52
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: nstoykov
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: nstoykov
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	media_app	streamingplatform
2	media_app	media
3	media_app	review
4	admin	logentry
5	auth	permission
6	auth	group
7	auth	user
8	contenttypes	contenttype
9	sessions	session
10	authtoken	token
11	authtoken	tokenproxy
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: nstoykov
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2024-09-11 16:42:26.955177+00
2	auth	0001_initial	2024-09-11 16:42:27.044166+00
3	admin	0001_initial	2024-09-11 16:42:27.066164+00
4	admin	0002_logentry_remove_auto_add	2024-09-11 16:42:27.072164+00
5	admin	0003_logentry_add_action_flag_choices	2024-09-11 16:42:27.079163+00
6	contenttypes	0002_remove_content_type_name	2024-09-11 16:42:27.0942+00
7	auth	0002_alter_permission_name_max_length	2024-09-11 16:42:27.102176+00
8	auth	0003_alter_user_email_max_length	2024-09-11 16:42:27.110192+00
9	auth	0004_alter_user_username_opts	2024-09-11 16:42:27.118186+00
10	auth	0005_alter_user_last_login_null	2024-09-11 16:42:27.1262+00
11	auth	0006_require_contenttypes_0002	2024-09-11 16:42:27.128199+00
12	auth	0007_alter_validators_add_error_messages	2024-09-11 16:42:27.134198+00
13	auth	0008_alter_user_username_max_length	2024-09-11 16:42:27.146168+00
14	auth	0009_alter_user_last_name_max_length	2024-09-11 16:42:27.154194+00
15	auth	0010_alter_group_name_max_length	2024-09-11 16:42:27.162192+00
16	auth	0011_update_proxy_permissions	2024-09-11 16:42:27.1692+00
17	auth	0012_alter_user_first_name_max_length	2024-09-11 16:42:27.177166+00
18	authtoken	0001_initial	2024-09-11 16:42:27.194179+00
19	authtoken	0002_auto_20160226_1747	2024-09-11 16:42:27.218182+00
20	authtoken	0003_tokenproxy	2024-09-11 16:42:27.221196+00
21	authtoken	0004_alter_tokenproxy_options	2024-09-11 16:42:27.22517+00
22	sessions	0001_initial	2024-09-11 16:42:27.237182+00
23	media_app	0001_initial	2024-09-11 16:57:41.432055+00
24	media_app	0002_alter_review_description	2024-09-12 13:58:38.738308+00
25	media_app	0003_remove_media_number_rating_alter_media_avg_rating	2024-09-13 06:25:21.623186+00
26	media_app	0004_alter_media_avg_rating	2024-09-13 06:31:12.591999+00
27	media_app	0005_media_user_rating_alter_media_avg_rating	2024-09-13 06:48:14.953856+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: nstoykov
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
8rhrafj9pj34e4o27l09nw39w38pfuyv	.eJxVjEsOAiEQBe_C2hBokI9L956BdEMrowaSYWZlvLtOMgvdvqp6L5FwXWpaB89pKuIktDj8boT5wW0D5Y7t1mXubZknkpsidzrkpRd-nnf376DiqN_ahmjBuGg9BfAK0DFyzMoVH9h4MgSYc4DCwZhgLYEm5CvGoy5ZaSPeH8dXN58:1sp07S:ueeczdJK9RopcFwQXnqIS1GHBIgpW7GBKZGl09oT1bc	2024-09-27 06:49:26.005852+00
\.


--
-- Data for Name: media_app_media; Type: TABLE DATA; Schema: public; Owner: nstoykov
--

COPY public.media_app_media (id, title, storyline, active, avg_rating, created, streaming_platform_id, user_rating) FROM stdin;
1	The Matrix	Movie description	t	3.3	2024-09-13 06:49:07.746855+00	5	5
2	Inception	Movie description	t	1.9	2024-09-13 06:49:07.749845+00	6	2
3	Interstellar	Movie description	t	1.8	2024-09-13 06:49:07.751855+00	5	2
4	The Dark Knight	Movie description	t	4.3	2024-09-13 06:49:07.752854+00	5	1
5	Pulp Fiction	Movie description	t	2.3	2024-09-13 06:49:07.752854+00	7	3
6	The Shawshank Redemption	Movie description	t	3.6	2024-09-13 06:49:07.753873+00	6	2
7	Fight Club	Movie description	t	4.9	2024-09-13 06:49:07.754883+00	6	3
8	Forrest Gump	Movie description	t	4.6	2024-09-13 06:49:07.755884+00	6	4
9	The Godfather	Movie description	t	2.9	2024-09-13 06:49:07.756881+00	5	5
10	Gladiator	Movie description	t	1.4	2024-09-13 06:49:07.757874+00	5	2
11	The Avengers	Movie description	t	3.4	2024-09-13 06:49:07.757874+00	5	2
12	Iron Man	Movie description	t	0.5	2024-09-13 06:49:07.758871+00	6	2
13	Spider-Man	Movie description	t	2.8	2024-09-13 06:49:07.759874+00	8	2
14	Guardians of the Galaxy	Movie description	t	0.7	2024-09-13 06:49:07.759874+00	7	5
15	Thor	Movie description	t	3.7	2024-09-13 06:49:07.760944+00	6	2
16	Star Wars	Movie description	t	1.9	2024-09-13 06:49:07.761941+00	5	3
17	The Empire Strikes Back	Movie description	t	3	2024-09-13 06:49:07.762957+00	5	2
18	Return of the Jedi	Movie description	t	3.6	2024-09-13 06:49:07.762957+00	6	4
19	The Force Awakens	Movie description	t	0.9	2024-09-13 06:49:07.763948+00	7	1
20	Avatar	Movie description	t	0.8	2024-09-13 06:49:07.764938+00	5	1
21	Jurassic Park	Movie description	t	1.3	2024-09-13 06:49:07.764938+00	7	5
22	The Lion King	Movie description	t	4.1	2024-09-13 06:49:07.765935+00	7	1
23	Toy Story	Movie description	t	0.7	2024-09-13 06:49:07.765935+00	6	1
24	Finding Nemo	Movie description	t	4.8	2024-09-13 06:49:07.766936+00	8	2
25	WALL-E	Movie description	t	1.9	2024-09-13 06:49:07.766936+00	5	5
26	Harry Potter	Movie description	t	4	2024-09-13 06:49:07.76791+00	7	4
27	The Hobbit	Movie description	t	3.2	2024-09-13 06:49:07.768845+00	5	2
28	The Lord of the Rings	Movie description	t	1	2024-09-13 06:49:07.769857+00	7	5
29	Batman Begins	Movie description	t	1.4	2024-09-13 06:49:07.770896+00	6	3
30	Shazam!	Movie description	t	2.6	2024-09-13 06:49:07.771844+00	5	4
\.


--
-- Data for Name: media_app_review; Type: TABLE DATA; Schema: public; Owner: nstoykov
--

COPY public.media_app_review (id, rating, description, active, created, update, media_id, reviewer_id) FROM stdin;
1	1	Review 1 description for Iron Man.	t	2024-09-13 06:49:07.839844+00	2024-09-13 06:49:07.839844+00	12	25
2	4	Review 2 description for Inception.	t	2024-09-13 06:49:07.842844+00	2024-09-13 06:49:07.842844+00	2	27
3	1	Review 3 description for Guardians of the Galaxy.	t	2024-09-13 06:49:07.843879+00	2024-09-13 06:49:07.843879+00	14	17
4	1	Review 4 description for The Godfather.	t	2024-09-13 06:49:07.844872+00	2024-09-13 06:49:07.844872+00	9	10
5	3	Review 5 description for Pulp Fiction.	t	2024-09-13 06:49:07.846872+00	2024-09-13 06:49:07.846872+00	5	10
6	1	Review 6 description for Guardians of the Galaxy.	t	2024-09-13 06:49:07.84788+00	2024-09-13 06:49:07.84788+00	14	8
7	3	Review 7 description for The Dark Knight.	t	2024-09-13 06:49:07.848877+00	2024-09-13 06:49:07.848877+00	4	39
8	1	Review 8 description for Spider-Man.	t	2024-09-13 06:49:07.84987+00	2024-09-13 06:49:07.84987+00	13	52
9	4	Review 9 description for The Hobbit.	t	2024-09-13 06:49:07.851859+00	2024-09-13 06:49:07.851859+00	27	22
10	4	Review 10 description for Forrest Gump.	t	2024-09-13 06:49:07.851859+00	2024-09-13 06:49:07.852878+00	8	14
11	5	Review 11 description for Star Wars.	t	2024-09-13 06:49:07.852878+00	2024-09-13 06:49:07.852878+00	16	4
12	5	Review 12 description for The Force Awakens.	t	2024-09-13 06:49:07.853872+00	2024-09-13 06:49:07.853872+00	19	10
13	3	Review 13 description for Fight Club.	t	2024-09-13 06:49:07.853872+00	2024-09-13 06:49:07.853872+00	7	6
14	1	Review 14 description for Forrest Gump.	t	2024-09-13 06:49:07.854872+00	2024-09-13 06:49:07.854872+00	8	45
15	2	Review 15 description for The Shawshank Redemption.	t	2024-09-13 06:49:07.85585+00	2024-09-13 06:49:07.85585+00	6	24
16	1	Review 16 description for The Avengers.	t	2024-09-13 06:49:07.85585+00	2024-09-13 06:49:07.85585+00	11	3
17	1	Review 17 description for The Godfather.	t	2024-09-13 06:49:07.856855+00	2024-09-13 06:49:07.856855+00	9	17
18	2	Review 18 description for Avatar.	t	2024-09-13 06:49:07.857889+00	2024-09-13 06:49:07.857889+00	20	36
19	5	Review 19 description for Harry Potter.	t	2024-09-13 06:49:07.858874+00	2024-09-13 06:49:07.858874+00	26	29
20	1	Review 20 description for Star Wars.	t	2024-09-13 06:49:07.859844+00	2024-09-13 06:49:07.859844+00	16	1
21	3	Review 21 description for The Hobbit.	t	2024-09-13 06:49:07.859844+00	2024-09-13 06:49:07.859844+00	27	6
22	1	Review 22 description for The Empire Strikes Back.	t	2024-09-13 06:49:07.860843+00	2024-09-13 06:49:07.860843+00	17	1
23	4	Review 23 description for The Lion King.	t	2024-09-13 06:49:07.861842+00	2024-09-13 06:49:07.861842+00	22	19
24	4	Review 24 description for The Dark Knight.	t	2024-09-13 06:49:07.861842+00	2024-09-13 06:49:07.861842+00	4	45
25	2	Review 25 description for Inception.	t	2024-09-13 06:49:07.862842+00	2024-09-13 06:49:07.862842+00	2	12
26	5	Review 26 description for The Matrix.	t	2024-09-13 06:49:07.862842+00	2024-09-13 06:49:07.862842+00	1	21
27	1	Review 27 description for Spider-Man.	t	2024-09-13 06:49:07.862842+00	2024-09-13 06:49:07.862842+00	13	41
28	5	Review 28 description for The Avengers.	t	2024-09-13 06:49:07.863841+00	2024-09-13 06:49:07.863841+00	11	17
29	3	Review 29 description for Toy Story.	t	2024-09-13 06:49:07.863841+00	2024-09-13 06:49:07.863841+00	23	20
30	2	Review 30 description for The Hobbit.	t	2024-09-13 06:49:07.864842+00	2024-09-13 06:49:07.864842+00	27	5
31	4	Review 31 description for The Force Awakens.	t	2024-09-13 06:49:07.864842+00	2024-09-13 06:49:07.864842+00	19	17
32	3	Review 32 description for Inception.	t	2024-09-13 06:49:07.865842+00	2024-09-13 06:49:07.865842+00	2	43
33	1	Review 33 description for Star Wars.	t	2024-09-13 06:49:07.865842+00	2024-09-13 06:49:07.865842+00	16	44
34	1	Review 34 description for The Dark Knight.	t	2024-09-13 06:49:07.866843+00	2024-09-13 06:49:07.866843+00	4	38
35	2	Review 35 description for Gladiator.	t	2024-09-13 06:49:07.866843+00	2024-09-13 06:49:07.866843+00	10	7
36	4	Review 36 description for Inception.	t	2024-09-13 06:49:07.867842+00	2024-09-13 06:49:07.867842+00	2	49
37	5	Review 37 description for Finding Nemo.	t	2024-09-13 06:49:07.867842+00	2024-09-13 06:49:07.867842+00	24	14
38	1	Review 38 description for Iron Man.	t	2024-09-13 06:49:07.868842+00	2024-09-13 06:49:07.868842+00	12	47
39	3	Review 39 description for Shazam!.	t	2024-09-13 06:49:07.869842+00	2024-09-13 06:49:07.869842+00	30	27
40	5	Review 40 description for The Godfather.	t	2024-09-13 06:49:07.870842+00	2024-09-13 06:49:07.870842+00	9	4
41	5	Review 41 description for Thor.	t	2024-09-13 06:49:07.870842+00	2024-09-13 06:49:07.870842+00	15	2
42	5	Review 42 description for The Matrix.	t	2024-09-13 06:49:07.871842+00	2024-09-13 06:49:07.871842+00	1	12
43	2	Review 43 description for Guardians of the Galaxy.	t	2024-09-13 06:49:07.872842+00	2024-09-13 06:49:07.872842+00	14	51
44	4	Review 44 description for Shazam!.	t	2024-09-13 06:49:07.872842+00	2024-09-13 06:49:07.872842+00	30	12
45	3	Review 45 description for The Hobbit.	t	2024-09-13 06:49:07.873842+00	2024-09-13 06:49:07.873842+00	27	43
46	4	Review 46 description for Guardians of the Galaxy.	t	2024-09-13 06:49:07.873842+00	2024-09-13 06:49:07.873842+00	14	27
47	4	Review 47 description for Return of the Jedi.	t	2024-09-13 06:49:07.874842+00	2024-09-13 06:49:07.874842+00	18	8
48	3	Review 48 description for Thor.	t	2024-09-13 06:49:07.874842+00	2024-09-13 06:49:07.874842+00	15	37
49	4	Review 49 description for Jurassic Park.	t	2024-09-13 06:49:07.875842+00	2024-09-13 06:49:07.875842+00	21	28
50	1	Review 50 description for Return of the Jedi.	t	2024-09-13 06:49:07.875842+00	2024-09-13 06:49:07.875842+00	18	10
51	2	Review 51 description for The Lion King.	t	2024-09-13 06:49:07.876842+00	2024-09-13 06:49:07.876842+00	22	6
52	4	Review 52 description for Pulp Fiction.	t	2024-09-13 06:49:07.877842+00	2024-09-13 06:49:07.877842+00	5	30
53	3	Review 53 description for Gladiator.	t	2024-09-13 06:49:07.878842+00	2024-09-13 06:49:07.878842+00	10	22
54	4	Review 54 description for The Lord of the Rings.	t	2024-09-13 06:49:07.878842+00	2024-09-13 06:49:07.878842+00	28	31
55	4	Review 55 description for Return of the Jedi.	t	2024-09-13 06:49:07.879842+00	2024-09-13 06:49:07.879842+00	18	33
56	5	Review 56 description for The Lion King.	t	2024-09-13 06:49:07.879842+00	2024-09-13 06:49:07.879842+00	22	6
57	1	Review 57 description for Interstellar.	t	2024-09-13 06:49:07.880842+00	2024-09-13 06:49:07.880842+00	3	33
58	5	Review 58 description for The Lion King.	t	2024-09-13 06:49:07.880842+00	2024-09-13 06:49:07.880842+00	22	17
59	1	Review 59 description for Finding Nemo.	t	2024-09-13 06:49:07.881842+00	2024-09-13 06:49:07.881842+00	24	35
60	5	Review 60 description for Inception.	t	2024-09-13 06:49:07.881842+00	2024-09-13 06:49:07.881842+00	2	49
61	5	Review 61 description for Finding Nemo.	t	2024-09-13 06:49:07.882842+00	2024-09-13 06:49:07.882842+00	24	8
62	5	Review 62 description for The Avengers.	t	2024-09-13 06:49:07.882842+00	2024-09-13 06:49:07.882842+00	11	23
63	4	Review 63 description for Pulp Fiction.	t	2024-09-13 06:49:07.883842+00	2024-09-13 06:49:07.883842+00	5	15
64	1	Review 64 description for The Godfather.	t	2024-09-13 06:49:07.883842+00	2024-09-13 06:49:07.883842+00	9	45
65	2	Review 65 description for Harry Potter.	t	2024-09-13 06:49:07.884842+00	2024-09-13 06:49:07.884842+00	26	22
66	2	Review 66 description for Jurassic Park.	t	2024-09-13 06:49:07.885842+00	2024-09-13 06:49:07.885842+00	21	49
67	5	Review 67 description for Iron Man.	t	2024-09-13 06:49:07.886842+00	2024-09-13 06:49:07.886842+00	12	5
68	4	Review 68 description for The Godfather.	t	2024-09-13 06:49:07.887842+00	2024-09-13 06:49:07.887842+00	9	16
69	5	Review 69 description for Avatar.	t	2024-09-13 06:49:07.887842+00	2024-09-13 06:49:07.887842+00	20	36
70	3	Review 70 description for Gladiator.	t	2024-09-13 06:49:07.888842+00	2024-09-13 06:49:07.888842+00	10	16
71	5	Review 71 description for Pulp Fiction.	t	2024-09-13 06:49:07.888842+00	2024-09-13 06:49:07.888842+00	5	23
72	4	Review 72 description for Interstellar.	t	2024-09-13 06:49:07.890842+00	2024-09-13 06:49:07.890842+00	3	24
73	1	Review 73 description for WALL-E.	t	2024-09-13 06:49:07.891863+00	2024-09-13 06:49:07.891863+00	25	26
74	2	Review 74 description for Thor.	t	2024-09-13 06:49:07.891863+00	2024-09-13 06:49:07.891863+00	15	43
75	2	Review 75 description for Fight Club.	t	2024-09-13 06:49:07.893852+00	2024-09-13 06:49:07.893852+00	7	36
76	4	Review 76 description for Harry Potter.	t	2024-09-13 06:49:07.894854+00	2024-09-13 06:49:07.894854+00	26	31
77	1	Review 77 description for The Avengers.	t	2024-09-13 06:49:07.895939+00	2024-09-13 06:49:07.895939+00	11	11
78	1	Review 78 description for WALL-E.	t	2024-09-13 06:49:07.895939+00	2024-09-13 06:49:07.895939+00	25	49
79	3	Review 79 description for Iron Man.	t	2024-09-13 06:49:07.896877+00	2024-09-13 06:49:07.896877+00	12	21
80	1	Review 80 description for Gladiator.	t	2024-09-13 06:49:07.896877+00	2024-09-13 06:49:07.896877+00	10	42
81	1	Review 81 description for The Dark Knight.	t	2024-09-13 06:49:07.897872+00	2024-09-13 06:49:07.897872+00	4	3
82	5	Review 82 description for WALL-E.	t	2024-09-13 06:49:07.897872+00	2024-09-13 06:49:07.897872+00	25	34
83	5	Review 83 description for Iron Man.	t	2024-09-13 06:49:07.898871+00	2024-09-13 06:49:07.898871+00	12	22
84	1	Review 84 description for The Lord of the Rings.	t	2024-09-13 06:49:07.898871+00	2024-09-13 06:49:07.898871+00	28	17
85	5	Review 85 description for The Lord of the Rings.	t	2024-09-13 06:49:07.899872+00	2024-09-13 06:49:07.899872+00	28	46
86	5	Review 86 description for Thor.	t	2024-09-13 06:49:07.899872+00	2024-09-13 06:49:07.899872+00	15	13
87	5	Review 87 description for Avatar.	t	2024-09-13 06:49:07.899872+00	2024-09-13 06:49:07.899872+00	20	30
88	4	Review 88 description for Gladiator.	t	2024-09-13 06:49:07.900855+00	2024-09-13 06:49:07.900855+00	10	46
89	1	Review 89 description for Inception.	t	2024-09-13 06:49:07.901858+00	2024-09-13 06:49:07.901858+00	2	41
90	4	Review 90 description for Avatar.	t	2024-09-13 06:49:07.902856+00	2024-09-13 06:49:07.902856+00	20	44
91	1	Review 91 description for Shazam!.	t	2024-09-13 06:49:07.902856+00	2024-09-13 06:49:07.902856+00	30	12
92	4	Review 92 description for Gladiator.	t	2024-09-13 06:49:07.903871+00	2024-09-13 06:49:07.903871+00	10	35
93	2	Review 93 description for The Avengers.	t	2024-09-13 06:49:07.904872+00	2024-09-13 06:49:07.904872+00	11	27
94	5	Review 94 description for Forrest Gump.	t	2024-09-13 06:49:07.904872+00	2024-09-13 06:49:07.904872+00	8	17
95	4	Review 95 description for The Shawshank Redemption.	t	2024-09-13 06:49:07.904872+00	2024-09-13 06:49:07.904872+00	6	48
96	4	Review 96 description for Interstellar.	t	2024-09-13 06:49:07.905871+00	2024-09-13 06:49:07.905871+00	3	27
97	5	Review 97 description for Finding Nemo.	t	2024-09-13 06:49:07.905871+00	2024-09-13 06:49:07.905871+00	24	42
98	2	Review 98 description for Guardians of the Galaxy.	t	2024-09-13 06:49:07.906873+00	2024-09-13 06:49:07.906873+00	14	3
99	4	Review 99 description for Toy Story.	t	2024-09-13 06:49:07.907857+00	2024-09-13 06:49:07.907857+00	23	2
100	1	Review 100 description for Return of the Jedi.	t	2024-09-13 06:49:07.907857+00	2024-09-13 06:49:07.907857+00	18	28
101	5	Review 101 description for Spider-Man.	t	2024-09-13 06:49:07.908874+00	2024-09-13 06:49:07.908874+00	13	27
102	5	Review 102 description for The Empire Strikes Back.	t	2024-09-13 06:49:07.909874+00	2024-09-13 06:49:07.909874+00	17	46
103	1	Review 103 description for The Lord of the Rings.	t	2024-09-13 06:49:07.910864+00	2024-09-13 06:49:07.910864+00	28	12
104	5	Review 104 description for Return of the Jedi.	t	2024-09-13 06:49:07.910864+00	2024-09-13 06:49:07.910864+00	18	36
105	4	Review 105 description for Avatar.	t	2024-09-13 06:49:07.911878+00	2024-09-13 06:49:07.911878+00	20	44
106	3	Review 106 description for Batman Begins.	t	2024-09-13 06:49:07.911878+00	2024-09-13 06:49:07.911878+00	29	28
107	3	Review 107 description for Inception.	t	2024-09-13 06:49:07.912877+00	2024-09-13 06:49:07.912877+00	2	41
108	3	Review 108 description for The Lord of the Rings.	t	2024-09-13 06:49:07.912877+00	2024-09-13 06:49:07.912877+00	28	5
109	2	Review 109 description for Batman Begins.	t	2024-09-13 06:49:07.913871+00	2024-09-13 06:49:07.913871+00	29	38
110	1	Review 110 description for The Lord of the Rings.	t	2024-09-13 06:49:07.913871+00	2024-09-13 06:49:07.913871+00	28	30
111	5	Review 111 description for Return of the Jedi.	t	2024-09-13 06:49:07.913871+00	2024-09-13 06:49:07.913871+00	18	13
112	3	Review 112 description for The Godfather.	t	2024-09-13 06:49:07.914871+00	2024-09-13 06:49:07.914871+00	9	22
113	2	Review 113 description for Avatar.	t	2024-09-13 06:49:07.914871+00	2024-09-13 06:49:07.914871+00	20	6
114	5	Review 114 description for The Matrix.	t	2024-09-13 06:49:07.91588+00	2024-09-13 06:49:07.91588+00	1	26
115	4	Review 115 description for Finding Nemo.	t	2024-09-13 06:49:07.91588+00	2024-09-13 06:49:07.91588+00	24	29
116	4	Review 116 description for The Force Awakens.	t	2024-09-13 06:49:07.916871+00	2024-09-13 06:49:07.916871+00	19	13
117	3	Review 117 description for Toy Story.	t	2024-09-13 06:49:07.916871+00	2024-09-13 06:49:07.916871+00	23	37
118	4	Review 118 description for The Avengers.	t	2024-09-13 06:49:07.917855+00	2024-09-13 06:49:07.917855+00	11	13
119	2	Review 119 description for Gladiator.	t	2024-09-13 06:49:07.918844+00	2024-09-13 06:49:07.918844+00	10	45
120	3	Review 120 description for Harry Potter.	t	2024-09-13 06:49:07.919872+00	2024-09-13 06:49:07.919872+00	26	27
121	3	Review 121 description for Shazam!.	t	2024-09-13 06:49:07.919872+00	2024-09-13 06:49:07.919872+00	30	16
122	2	Review 122 description for The Hobbit.	t	2024-09-13 06:49:07.920879+00	2024-09-13 06:49:07.920879+00	27	39
123	3	Review 123 description for Batman Begins.	t	2024-09-13 06:49:07.920879+00	2024-09-13 06:49:07.920879+00	29	38
124	1	Review 124 description for Return of the Jedi.	t	2024-09-13 06:49:07.921872+00	2024-09-13 06:49:07.921872+00	18	49
125	3	Review 125 description for Jurassic Park.	t	2024-09-13 06:49:07.921872+00	2024-09-13 06:49:07.921872+00	21	8
126	1	Review 126 description for The Empire Strikes Back.	t	2024-09-13 06:49:07.921872+00	2024-09-13 06:49:07.921872+00	17	52
127	2	Review 127 description for Inception.	t	2024-09-13 06:49:07.922871+00	2024-09-13 06:49:07.922871+00	2	8
128	4	Review 128 description for Spider-Man.	t	2024-09-13 06:49:07.923855+00	2024-09-13 06:49:07.923855+00	13	39
129	3	Review 129 description for Thor.	t	2024-09-13 06:49:07.924861+00	2024-09-13 06:49:07.924861+00	15	49
130	4	Review 130 description for Forrest Gump.	t	2024-09-13 06:49:07.925844+00	2024-09-13 06:49:07.925844+00	8	49
131	3	Review 131 description for Guardians of the Galaxy.	t	2024-09-13 06:49:07.926856+00	2024-09-13 06:49:07.926856+00	14	32
132	1	Review 132 description for Finding Nemo.	t	2024-09-13 06:49:07.926856+00	2024-09-13 06:49:07.926856+00	24	52
133	1	Review 133 description for The Godfather.	t	2024-09-13 06:49:07.927877+00	2024-09-13 06:49:07.927877+00	9	15
134	2	Review 134 description for Return of the Jedi.	t	2024-09-13 06:49:07.928875+00	2024-09-13 06:49:07.928875+00	18	2
135	2	Review 135 description for Return of the Jedi.	t	2024-09-13 06:49:07.928875+00	2024-09-13 06:49:07.928875+00	18	50
136	4	Review 136 description for Batman Begins.	t	2024-09-13 06:49:07.929873+00	2024-09-13 06:49:07.929873+00	29	48
137	2	Review 137 description for Gladiator.	t	2024-09-13 06:49:07.929873+00	2024-09-13 06:49:07.929873+00	10	1
138	1	Review 138 description for The Dark Knight.	t	2024-09-13 06:49:07.929873+00	2024-09-13 06:49:07.929873+00	4	40
139	3	Review 139 description for The Dark Knight.	t	2024-09-13 06:49:07.930872+00	2024-09-13 06:49:07.930872+00	4	47
140	3	Review 140 description for Spider-Man.	t	2024-09-13 06:49:07.930872+00	2024-09-13 06:49:07.930872+00	13	11
141	5	Review 141 description for Spider-Man.	t	2024-09-13 06:49:07.931876+00	2024-09-13 06:49:07.931876+00	13	42
142	3	Review 142 description for Batman Begins.	t	2024-09-13 06:49:07.931876+00	2024-09-13 06:49:07.931876+00	29	28
143	2	Review 143 description for The Force Awakens.	t	2024-09-13 06:49:07.932872+00	2024-09-13 06:49:07.932872+00	19	41
144	3	Review 144 description for The Empire Strikes Back.	t	2024-09-13 06:49:07.93387+00	2024-09-13 06:49:07.93387+00	17	48
145	4	Review 145 description for Toy Story.	t	2024-09-13 06:49:07.93387+00	2024-09-13 06:49:07.93387+00	23	52
146	3	Review 146 description for Star Wars.	t	2024-09-13 06:49:07.934845+00	2024-09-13 06:49:07.934845+00	16	43
147	4	Review 147 description for The Empire Strikes Back.	t	2024-09-13 06:49:07.935878+00	2024-09-13 06:49:07.935878+00	17	17
148	1	Review 148 description for Guardians of the Galaxy.	t	2024-09-13 06:49:07.935878+00	2024-09-13 06:49:07.935878+00	14	16
149	1	Review 149 description for Forrest Gump.	t	2024-09-13 06:49:07.936874+00	2024-09-13 06:49:07.936874+00	8	36
150	3	Review 150 description for Guardians of the Galaxy.	t	2024-09-13 06:49:07.936874+00	2024-09-13 06:49:07.936874+00	14	4
151	1	Review 151 description for Thor.	t	2024-09-13 06:49:07.937873+00	2024-09-13 06:49:07.937873+00	15	22
152	1	Review 152 description for Shazam!.	t	2024-09-13 06:49:07.937873+00	2024-09-13 06:49:07.937873+00	30	13
153	1	Review 153 description for The Lord of the Rings.	t	2024-09-13 06:49:07.938874+00	2024-09-13 06:49:07.938874+00	28	33
154	3	Review 154 description for The Lord of the Rings.	t	2024-09-13 06:49:07.938874+00	2024-09-13 06:49:07.938874+00	28	25
155	4	Review 155 description for The Godfather.	t	2024-09-13 06:49:07.939853+00	2024-09-13 06:49:07.939853+00	9	2
156	5	Review 156 description for Inception.	t	2024-09-13 06:49:07.940853+00	2024-09-13 06:49:07.940853+00	2	49
157	4	Review 157 description for The Shawshank Redemption.	t	2024-09-13 06:49:07.940853+00	2024-09-13 06:49:07.940853+00	6	1
158	2	Review 158 description for Return of the Jedi.	t	2024-09-13 06:49:07.941877+00	2024-09-13 06:49:07.941877+00	18	32
159	3	Review 159 description for Return of the Jedi.	t	2024-09-13 06:49:07.94288+00	2024-09-13 06:49:07.94288+00	18	16
160	5	Review 160 description for The Lion King.	t	2024-09-13 06:49:07.94288+00	2024-09-13 06:49:07.94288+00	22	44
161	3	Review 161 description for The Lion King.	t	2024-09-13 06:49:07.943872+00	2024-09-13 06:49:07.943872+00	22	7
162	5	Review 162 description for The Shawshank Redemption.	t	2024-09-13 06:49:07.943872+00	2024-09-13 06:49:07.943872+00	6	50
163	2	Review 163 description for The Force Awakens.	t	2024-09-13 06:49:07.944879+00	2024-09-13 06:49:07.944879+00	19	29
164	3	Review 164 description for The Force Awakens.	t	2024-09-13 06:49:07.944879+00	2024-09-13 06:49:07.944879+00	19	29
165	4	Review 165 description for Iron Man.	t	2024-09-13 06:49:07.945873+00	2024-09-13 06:49:07.945873+00	12	44
166	3	Review 166 description for The Matrix.	t	2024-09-13 06:49:07.945873+00	2024-09-13 06:49:07.945873+00	1	3
167	1	Review 167 description for Fight Club.	t	2024-09-13 06:49:07.946872+00	2024-09-13 06:49:07.946872+00	7	51
168	4	Review 168 description for Jurassic Park.	t	2024-09-13 06:49:07.946872+00	2024-09-13 06:49:07.946872+00	21	46
169	4	Review 169 description for Star Wars.	t	2024-09-13 06:49:07.946872+00	2024-09-13 06:49:07.946872+00	16	9
170	1	Review 170 description for The Hobbit.	t	2024-09-13 06:49:07.947876+00	2024-09-13 06:49:07.947876+00	27	15
171	3	Review 171 description for Fight Club.	t	2024-09-13 06:49:07.947876+00	2024-09-13 06:49:07.947876+00	7	16
172	1	Review 172 description for The Dark Knight.	t	2024-09-13 06:49:07.948871+00	2024-09-13 06:49:07.948871+00	4	47
173	2	Review 173 description for Spider-Man.	t	2024-09-13 06:49:07.949873+00	2024-09-13 06:49:07.949873+00	13	20
174	2	Review 174 description for The Dark Knight.	t	2024-09-13 06:49:07.949873+00	2024-09-13 06:49:07.949873+00	4	17
175	2	Review 175 description for The Matrix.	t	2024-09-13 06:49:07.950864+00	2024-09-13 06:49:07.950864+00	1	23
176	2	Review 176 description for Batman Begins.	t	2024-09-13 06:49:07.950864+00	2024-09-13 06:49:07.950864+00	29	16
177	4	Review 177 description for Avatar.	t	2024-09-13 06:49:07.951856+00	2024-09-13 06:49:07.951856+00	20	22
178	1	Review 178 description for Jurassic Park.	t	2024-09-13 06:49:07.952881+00	2024-09-13 06:49:07.952881+00	21	49
179	5	Review 179 description for The Matrix.	t	2024-09-13 06:49:07.952881+00	2024-09-13 06:49:07.952881+00	1	4
180	5	Review 180 description for The Shawshank Redemption.	t	2024-09-13 06:49:07.953878+00	2024-09-13 06:49:07.953878+00	6	40
181	4	Review 181 description for Spider-Man.	t	2024-09-13 06:49:07.953878+00	2024-09-13 06:49:07.953878+00	13	7
182	2	Review 182 description for The Hobbit.	t	2024-09-13 06:49:07.954871+00	2024-09-13 06:49:07.954871+00	27	18
183	3	Review 183 description for The Matrix.	t	2024-09-13 06:49:07.954871+00	2024-09-13 06:49:07.954871+00	1	20
184	4	Review 184 description for The Matrix.	t	2024-09-13 06:49:07.955879+00	2024-09-13 06:49:07.955879+00	1	47
185	3	Review 185 description for The Lord of the Rings.	t	2024-09-13 06:49:07.955879+00	2024-09-13 06:49:07.955879+00	28	10
186	4	Review 186 description for The Lion King.	t	2024-09-13 06:49:07.956872+00	2024-09-13 06:49:07.956872+00	22	22
187	2	Review 187 description for The Lord of the Rings.	t	2024-09-13 06:49:07.957872+00	2024-09-13 06:49:07.957872+00	28	14
188	5	Review 188 description for Star Wars.	t	2024-09-13 06:49:07.957872+00	2024-09-13 06:49:07.957872+00	16	27
189	4	Review 189 description for The Hobbit.	t	2024-09-13 06:49:07.958855+00	2024-09-13 06:49:07.958855+00	27	33
190	4	Review 190 description for Jurassic Park.	t	2024-09-13 06:49:07.959871+00	2024-09-13 06:49:07.959871+00	21	13
191	3	Review 191 description for Return of the Jedi.	t	2024-09-13 06:49:07.959871+00	2024-09-13 06:49:07.959871+00	18	32
192	3	Review 192 description for Toy Story.	t	2024-09-13 06:49:07.960871+00	2024-09-13 06:49:07.960871+00	23	26
193	2	Review 193 description for Fight Club.	t	2024-09-13 06:49:07.960871+00	2024-09-13 06:49:07.960871+00	7	21
194	3	Review 194 description for Return of the Jedi.	t	2024-09-13 06:49:07.961885+00	2024-09-13 06:49:07.961885+00	18	23
195	2	Review 195 description for The Lion King.	t	2024-09-13 06:49:07.961885+00	2024-09-13 06:49:07.961885+00	22	43
196	1	Review 196 description for Finding Nemo.	t	2024-09-13 06:49:07.962871+00	2024-09-13 06:49:07.962871+00	24	49
197	2	Review 197 description for Spider-Man.	t	2024-09-13 06:49:07.962871+00	2024-09-13 06:49:07.962871+00	13	10
198	3	Review 198 description for Gladiator.	t	2024-09-13 06:49:07.963875+00	2024-09-13 06:49:07.963875+00	10	16
199	1	Review 199 description for Star Wars.	t	2024-09-13 06:49:07.963875+00	2024-09-13 06:49:07.963875+00	16	23
200	4	Review 200 description for Shazam!.	t	2024-09-13 06:49:07.964871+00	2024-09-13 06:49:07.964871+00	30	14
201	3	Review 201 description for Finding Nemo.	t	2024-09-13 06:49:07.964871+00	2024-09-13 06:49:07.964871+00	24	10
202	1	Review 202 description for Iron Man.	t	2024-09-13 06:49:07.965879+00	2024-09-13 06:49:07.965879+00	12	16
203	3	Review 203 description for The Lion King.	t	2024-09-13 06:49:07.96688+00	2024-09-13 06:49:07.96688+00	22	7
204	5	Review 204 description for The Lord of the Rings.	t	2024-09-13 06:49:07.96688+00	2024-09-13 06:49:07.96688+00	28	40
205	2	Review 205 description for The Shawshank Redemption.	t	2024-09-13 06:49:07.967843+00	2024-09-13 06:49:07.967843+00	6	19
206	3	Review 206 description for WALL-E.	t	2024-09-13 06:49:07.967843+00	2024-09-13 06:49:07.967843+00	25	24
207	1	Review 207 description for Pulp Fiction.	t	2024-09-13 06:49:07.968856+00	2024-09-13 06:49:07.968856+00	5	5
208	3	Review 208 description for Iron Man.	t	2024-09-13 06:49:07.969872+00	2024-09-13 06:49:07.969872+00	12	25
209	2	Review 209 description for The Force Awakens.	t	2024-09-13 06:49:07.969872+00	2024-09-13 06:49:07.969872+00	19	3
210	4	Review 210 description for Finding Nemo.	t	2024-09-13 06:49:07.970882+00	2024-09-13 06:49:07.970882+00	24	32
211	3	Review 211 description for The Godfather.	t	2024-09-13 06:49:07.971873+00	2024-09-13 06:49:07.971873+00	9	38
212	5	Review 212 description for Star Wars.	t	2024-09-13 06:49:07.97287+00	2024-09-13 06:49:07.97287+00	16	16
213	2	Review 213 description for The Dark Knight.	t	2024-09-13 06:49:07.97287+00	2024-09-13 06:49:07.97287+00	4	6
214	4	Review 214 description for The Avengers.	t	2024-09-13 06:49:07.973857+00	2024-09-13 06:49:07.973857+00	11	52
215	2	Review 215 description for The Avengers.	t	2024-09-13 06:49:07.973857+00	2024-09-13 06:49:07.973857+00	11	52
216	4	Review 216 description for The Godfather.	t	2024-09-13 06:49:07.974881+00	2024-09-13 06:49:07.974881+00	9	39
217	5	Review 217 description for The Hobbit.	t	2024-09-13 06:49:07.975874+00	2024-09-13 06:49:07.975874+00	27	35
218	3	Review 218 description for Shazam!.	t	2024-09-13 06:49:07.975874+00	2024-09-13 06:49:07.975874+00	30	46
219	5	Review 219 description for Jurassic Park.	t	2024-09-13 06:49:07.976871+00	2024-09-13 06:49:07.976871+00	21	3
220	1	Review 220 description for The Hobbit.	t	2024-09-13 06:49:07.977874+00	2024-09-13 06:49:07.977874+00	27	45
221	2	Review 221 description for Spider-Man.	t	2024-09-13 06:49:07.978871+00	2024-09-13 06:49:07.978871+00	13	6
222	5	Review 222 description for The Dark Knight.	t	2024-09-13 06:49:07.978871+00	2024-09-13 06:49:07.978871+00	4	24
223	2	Review 223 description for Forrest Gump.	t	2024-09-13 06:49:07.979883+00	2024-09-13 06:49:07.979883+00	8	34
224	5	Review 224 description for Avatar.	t	2024-09-13 06:49:07.980872+00	2024-09-13 06:49:07.980872+00	20	14
225	2	Review 225 description for Guardians of the Galaxy.	t	2024-09-13 06:49:07.981859+00	2024-09-13 06:49:07.981859+00	14	11
226	5	Review 226 description for Interstellar.	t	2024-09-13 06:49:07.981859+00	2024-09-13 06:49:07.981859+00	3	37
227	2	Review 227 description for Batman Begins.	t	2024-09-13 06:49:07.982856+00	2024-09-13 06:49:07.982856+00	29	11
228	3	Review 228 description for Iron Man.	t	2024-09-13 06:49:07.983876+00	2024-09-13 06:49:07.983876+00	12	29
229	2	Review 229 description for Iron Man.	t	2024-09-13 06:49:07.983876+00	2024-09-13 06:49:07.983876+00	12	44
230	3	Review 230 description for Harry Potter.	t	2024-09-13 06:49:07.984847+00	2024-09-13 06:49:07.984847+00	26	20
231	5	Review 231 description for The Avengers.	t	2024-09-13 06:49:07.985879+00	2024-09-13 06:49:07.985879+00	11	35
232	4	Review 232 description for Interstellar.	t	2024-09-13 06:49:07.985879+00	2024-09-13 06:49:07.985879+00	3	8
233	4	Review 233 description for The Force Awakens.	t	2024-09-13 06:49:07.986873+00	2024-09-13 06:49:07.986873+00	19	15
234	4	Review 234 description for Iron Man.	t	2024-09-13 06:49:07.98786+00	2024-09-13 06:49:07.98786+00	12	26
235	1	Review 235 description for Fight Club.	t	2024-09-13 06:49:07.988854+00	2024-09-13 06:49:07.988854+00	7	40
236	4	Review 236 description for Shazam!.	t	2024-09-13 06:49:07.988854+00	2024-09-13 06:49:07.988854+00	30	5
237	2	Review 237 description for WALL-E.	t	2024-09-13 06:49:07.989859+00	2024-09-13 06:49:07.989859+00	25	18
238	2	Review 238 description for The Lord of the Rings.	t	2024-09-13 06:49:07.990858+00	2024-09-13 06:49:07.990858+00	28	43
239	5	Review 239 description for Fight Club.	t	2024-09-13 06:49:07.990858+00	2024-09-13 06:49:07.990858+00	7	43
240	4	Review 240 description for Star Wars.	t	2024-09-13 06:49:07.991858+00	2024-09-13 06:49:07.991858+00	16	21
241	5	Review 241 description for Toy Story.	t	2024-09-13 06:49:07.991858+00	2024-09-13 06:49:07.991858+00	23	17
242	3	Review 242 description for The Shawshank Redemption.	t	2024-09-13 06:49:07.992856+00	2024-09-13 06:49:07.992856+00	6	13
243	1	Review 243 description for Pulp Fiction.	t	2024-09-13 06:49:07.992856+00	2024-09-13 06:49:07.992856+00	5	42
244	3	Review 244 description for The Matrix.	t	2024-09-13 06:49:07.993857+00	2024-09-13 06:49:07.993857+00	1	8
245	5	Review 245 description for Avatar.	t	2024-09-13 06:49:07.993857+00	2024-09-13 06:49:07.993857+00	20	22
246	5	Review 246 description for The Lord of the Rings.	t	2024-09-13 06:49:07.994848+00	2024-09-13 06:49:07.994848+00	28	10
247	3	Review 247 description for Spider-Man.	t	2024-09-13 06:49:07.994848+00	2024-09-13 06:49:07.994848+00	13	12
248	2	Review 248 description for Iron Man.	t	2024-09-13 06:49:07.995843+00	2024-09-13 06:49:07.995843+00	12	7
249	5	Review 249 description for Return of the Jedi.	t	2024-09-13 06:49:07.995843+00	2024-09-13 06:49:07.995843+00	18	27
250	4	Review 250 description for The Shawshank Redemption.	t	2024-09-13 06:49:07.996842+00	2024-09-13 06:49:07.996842+00	6	45
251	2	Review 251 description for The Shawshank Redemption.	t	2024-09-13 06:49:07.996842+00	2024-09-13 06:49:07.996842+00	6	11
252	5	Review 252 description for The Hobbit.	t	2024-09-13 06:49:07.997868+00	2024-09-13 06:49:07.997868+00	27	25
253	4	Review 253 description for The Empire Strikes Back.	t	2024-09-13 06:49:07.998855+00	2024-09-13 06:49:07.998855+00	17	16
254	4	Review 254 description for Avatar.	t	2024-09-13 06:49:07.998855+00	2024-09-13 06:49:07.998855+00	20	18
255	5	Review 255 description for Star Wars.	t	2024-09-13 06:49:07.999843+00	2024-09-13 06:49:07.999843+00	16	16
256	5	Review 256 description for The Empire Strikes Back.	t	2024-09-13 06:49:07.999843+00	2024-09-13 06:49:07.999843+00	17	5
257	4	Review 257 description for Inception.	t	2024-09-13 06:49:08.000854+00	2024-09-13 06:49:08.000854+00	2	28
258	3	Review 258 description for Harry Potter.	t	2024-09-13 06:49:08.001845+00	2024-09-13 06:49:08.001845+00	26	35
259	4	Review 259 description for Harry Potter.	t	2024-09-13 06:49:08.002877+00	2024-09-13 06:49:08.002877+00	26	26
260	2	Review 260 description for Spider-Man.	t	2024-09-13 06:49:08.002877+00	2024-09-13 06:49:08.002877+00	13	49
261	5	Review 261 description for Fight Club.	t	2024-09-13 06:49:08.003872+00	2024-09-13 06:49:08.003872+00	7	45
262	5	Review 262 description for Thor.	t	2024-09-13 06:49:08.003872+00	2024-09-13 06:49:08.003872+00	15	32
263	3	Review 263 description for Harry Potter.	t	2024-09-13 06:49:08.003872+00	2024-09-13 06:49:08.003872+00	26	30
264	5	Review 264 description for Star Wars.	t	2024-09-13 06:49:08.004871+00	2024-09-13 06:49:08.004871+00	16	19
265	1	Review 265 description for WALL-E.	t	2024-09-13 06:49:08.005874+00	2024-09-13 06:49:08.005874+00	25	25
266	4	Review 266 description for Inception.	t	2024-09-13 06:49:08.005874+00	2024-09-13 06:49:08.005874+00	2	37
267	4	Review 267 description for The Lion King.	t	2024-09-13 06:49:08.006875+00	2024-09-13 06:49:08.006875+00	22	38
268	5	Review 268 description for Spider-Man.	t	2024-09-13 06:49:08.006875+00	2024-09-13 06:49:08.006875+00	13	24
269	4	Review 269 description for WALL-E.	t	2024-09-13 06:49:08.007871+00	2024-09-13 06:49:08.007871+00	25	23
270	5	Review 270 description for The Shawshank Redemption.	t	2024-09-13 06:49:08.007871+00	2024-09-13 06:49:08.007871+00	6	46
271	3	Review 271 description for The Force Awakens.	t	2024-09-13 06:49:08.007871+00	2024-09-13 06:49:08.007871+00	19	42
272	4	Review 272 description for Pulp Fiction.	t	2024-09-13 06:49:08.008872+00	2024-09-13 06:49:08.008872+00	5	12
273	4	Review 273 description for Interstellar.	t	2024-09-13 06:49:08.008872+00	2024-09-13 06:49:08.008872+00	3	21
274	4	Review 274 description for The Avengers.	t	2024-09-13 06:49:08.009879+00	2024-09-13 06:49:08.009879+00	11	29
275	3	Review 275 description for Star Wars.	t	2024-09-13 06:49:08.009879+00	2024-09-13 06:49:08.009879+00	16	45
276	5	Review 276 description for Finding Nemo.	t	2024-09-13 06:49:08.010872+00	2024-09-13 06:49:08.010872+00	24	13
277	2	Review 277 description for Return of the Jedi.	t	2024-09-13 06:49:08.010872+00	2024-09-13 06:49:08.010872+00	18	40
278	2	Review 278 description for Fight Club.	t	2024-09-13 06:49:08.01187+00	2024-09-13 06:49:08.01187+00	7	9
279	3	Review 279 description for Inception.	t	2024-09-13 06:49:08.01187+00	2024-09-13 06:49:08.01187+00	2	6
280	5	Review 280 description for Thor.	t	2024-09-13 06:49:08.01287+00	2024-09-13 06:49:08.01287+00	15	44
281	1	Review 281 description for Gladiator.	t	2024-09-13 06:49:08.013871+00	2024-09-13 06:49:08.013871+00	10	40
282	3	Review 282 description for Batman Begins.	t	2024-09-13 06:49:08.013871+00	2024-09-13 06:49:08.013871+00	29	26
283	3	Review 283 description for The Force Awakens.	t	2024-09-13 06:49:08.014874+00	2024-09-13 06:49:08.014874+00	19	13
284	1	Review 284 description for Jurassic Park.	t	2024-09-13 06:49:08.014874+00	2024-09-13 06:49:08.014874+00	21	9
285	5	Review 285 description for Shazam!.	t	2024-09-13 06:49:08.015872+00	2024-09-13 06:49:08.015872+00	30	1
286	5	Review 286 description for WALL-E.	t	2024-09-13 06:49:08.015872+00	2024-09-13 06:49:08.015872+00	25	8
287	5	Review 287 description for The Matrix.	t	2024-09-13 06:49:08.016873+00	2024-09-13 06:49:08.016873+00	1	30
288	4	Review 288 description for Pulp Fiction.	t	2024-09-13 06:49:08.016873+00	2024-09-13 06:49:08.016873+00	5	36
289	2	Review 289 description for Shazam!.	t	2024-09-13 06:49:08.017845+00	2024-09-13 06:49:08.017845+00	30	11
290	3	Review 290 description for Return of the Jedi.	t	2024-09-13 06:49:08.017845+00	2024-09-13 06:49:08.017845+00	18	21
291	5	Review 291 description for Harry Potter.	t	2024-09-13 06:49:08.018858+00	2024-09-13 06:49:08.018858+00	26	14
292	5	Review 292 description for WALL-E.	t	2024-09-13 06:49:08.019845+00	2024-09-13 06:49:08.019845+00	25	42
293	5	Review 293 description for Return of the Jedi.	t	2024-09-13 06:49:08.020874+00	2024-09-13 06:49:08.020874+00	18	21
294	1	Review 294 description for Shazam!.	t	2024-09-13 06:49:08.020874+00	2024-09-13 06:49:08.020874+00	30	48
295	1	Review 295 description for WALL-E.	t	2024-09-13 06:49:08.020874+00	2024-09-13 06:49:08.020874+00	25	52
296	5	Review 296 description for Pulp Fiction.	t	2024-09-13 06:49:08.021871+00	2024-09-13 06:49:08.021871+00	5	12
297	4	Review 297 description for Shazam!.	t	2024-09-13 06:49:08.022872+00	2024-09-13 06:49:08.022872+00	30	49
298	1	Review 298 description for Star Wars.	t	2024-09-13 06:49:08.022872+00	2024-09-13 06:49:08.022872+00	16	45
299	5	Review 299 description for The Lord of the Rings.	t	2024-09-13 06:49:08.023879+00	2024-09-13 06:49:08.023879+00	28	32
300	5	Review 300 description for The Godfather.	t	2024-09-13 06:49:08.023879+00	2024-09-13 06:49:08.023879+00	9	8
301	5	Review 301 description for The Avengers.	t	2024-09-13 06:49:08.024874+00	2024-09-13 06:49:08.024874+00	11	2
302	3	Review 302 description for Toy Story.	t	2024-09-13 06:49:08.024874+00	2024-09-13 06:49:08.024874+00	23	40
303	2	Review 303 description for The Lord of the Rings.	t	2024-09-13 06:49:08.024874+00	2024-09-13 06:49:08.024874+00	28	20
304	2	Review 304 description for Thor.	t	2024-09-13 06:49:08.025877+00	2024-09-13 06:49:08.025877+00	15	2
305	4	Review 305 description for The Matrix.	t	2024-09-13 06:49:08.025877+00	2024-09-13 06:49:08.025877+00	1	27
306	5	Review 306 description for Spider-Man.	t	2024-09-13 06:49:08.02687+00	2024-09-13 06:49:08.02687+00	13	11
307	3	Review 307 description for The Matrix.	t	2024-09-13 06:49:08.02687+00	2024-09-13 06:49:08.02687+00	1	27
308	2	Review 308 description for The Avengers.	t	2024-09-13 06:49:08.027877+00	2024-09-13 06:49:08.027877+00	11	48
309	5	Review 309 description for Return of the Jedi.	t	2024-09-13 06:49:08.027877+00	2024-09-13 06:49:08.027877+00	18	1
310	1	Review 310 description for The Matrix.	t	2024-09-13 06:49:08.02888+00	2024-09-13 06:49:08.02888+00	1	30
311	5	Review 311 description for Finding Nemo.	t	2024-09-13 06:49:08.02888+00	2024-09-13 06:49:08.02888+00	24	34
312	3	Review 312 description for The Godfather.	t	2024-09-13 06:49:08.029872+00	2024-09-13 06:49:08.029872+00	9	27
313	1	Review 313 description for Fight Club.	t	2024-09-13 06:49:08.030879+00	2024-09-13 06:49:08.030879+00	7	3
314	1	Review 314 description for Inception.	t	2024-09-13 06:49:08.030879+00	2024-09-13 06:49:08.030879+00	2	42
315	3	Review 315 description for Thor.	t	2024-09-13 06:49:08.031871+00	2024-09-13 06:49:08.031871+00	15	48
316	5	Review 316 description for The Empire Strikes Back.	t	2024-09-13 06:49:08.031871+00	2024-09-13 06:49:08.031871+00	17	26
317	2	Review 317 description for Return of the Jedi.	t	2024-09-13 06:49:08.032886+00	2024-09-13 06:49:08.032886+00	18	15
318	4	Review 318 description for Batman Begins.	t	2024-09-13 06:49:08.032886+00	2024-09-13 06:49:08.032886+00	29	24
319	3	Review 319 description for Iron Man.	t	2024-09-13 06:49:08.033877+00	2024-09-13 06:49:08.033877+00	12	28
320	3	Review 320 description for The Matrix.	t	2024-09-13 06:49:08.034845+00	2024-09-13 06:49:08.034845+00	1	45
321	4	Review 321 description for Interstellar.	t	2024-09-13 06:49:08.035857+00	2024-09-13 06:49:08.035857+00	3	12
322	3	Review 322 description for The Dark Knight.	t	2024-09-13 06:49:08.036844+00	2024-09-13 06:49:08.036844+00	4	21
323	4	Review 323 description for Fight Club.	t	2024-09-13 06:49:08.037857+00	2024-09-13 06:49:08.037857+00	7	33
324	4	Review 324 description for The Empire Strikes Back.	t	2024-09-13 06:49:08.038857+00	2024-09-13 06:49:08.038857+00	17	18
325	2	Review 325 description for Avatar.	t	2024-09-13 06:49:08.039873+00	2024-09-13 06:49:08.039873+00	20	3
326	3	Review 326 description for Iron Man.	t	2024-09-13 06:49:08.039873+00	2024-09-13 06:49:08.039873+00	12	42
327	1	Review 327 description for Harry Potter.	t	2024-09-13 06:49:08.040888+00	2024-09-13 06:49:08.040888+00	26	16
328	5	Review 328 description for The Lion King.	t	2024-09-13 06:49:08.040888+00	2024-09-13 06:49:08.040888+00	22	6
329	1	Review 329 description for Thor.	t	2024-09-13 06:49:08.041873+00	2024-09-13 06:49:08.041873+00	15	29
330	3	Review 330 description for Batman Begins.	t	2024-09-13 06:49:08.041873+00	2024-09-13 06:49:08.041873+00	29	11
331	4	Review 331 description for Avatar.	t	2024-09-13 06:49:08.042871+00	2024-09-13 06:49:08.042871+00	20	19
332	3	Review 332 description for Spider-Man.	t	2024-09-13 06:49:08.042871+00	2024-09-13 06:49:08.042871+00	13	19
333	3	Review 333 description for Finding Nemo.	t	2024-09-13 06:49:08.043876+00	2024-09-13 06:49:08.043876+00	24	2
334	1	Review 334 description for Spider-Man.	t	2024-09-13 06:49:08.044874+00	2024-09-13 06:49:08.044874+00	13	27
335	2	Review 335 description for Gladiator.	t	2024-09-13 06:49:08.044874+00	2024-09-13 06:49:08.044874+00	10	48
336	1	Review 336 description for Harry Potter.	t	2024-09-13 06:49:08.045855+00	2024-09-13 06:49:08.045855+00	26	42
337	4	Review 337 description for Forrest Gump.	t	2024-09-13 06:49:08.046882+00	2024-09-13 06:49:08.046882+00	8	6
338	5	Review 338 description for Pulp Fiction.	t	2024-09-13 06:49:08.046882+00	2024-09-13 06:49:08.046882+00	5	50
339	2	Review 339 description for Spider-Man.	t	2024-09-13 06:49:08.047872+00	2024-09-13 06:49:08.047872+00	13	45
340	3	Review 340 description for The Avengers.	t	2024-09-13 06:49:08.047872+00	2024-09-13 06:49:08.047872+00	11	46
341	4	Review 341 description for The Godfather.	t	2024-09-13 06:49:08.048872+00	2024-09-13 06:49:08.048872+00	9	16
342	4	Review 342 description for The Matrix.	t	2024-09-13 06:49:08.048872+00	2024-09-13 06:49:08.048872+00	1	25
343	5	Review 343 description for Interstellar.	t	2024-09-13 06:49:08.049884+00	2024-09-13 06:49:08.049884+00	3	11
344	2	Review 344 description for The Lion King.	t	2024-09-13 06:49:08.049884+00	2024-09-13 06:49:08.049884+00	22	47
345	2	Review 345 description for Gladiator.	t	2024-09-13 06:49:08.050844+00	2024-09-13 06:49:08.050844+00	10	21
346	1	Review 346 description for Spider-Man.	t	2024-09-13 06:49:08.051858+00	2024-09-13 06:49:08.051858+00	13	34
347	5	Review 347 description for Finding Nemo.	t	2024-09-13 06:49:08.052862+00	2024-09-13 06:49:08.052862+00	24	38
348	4	Review 348 description for The Shawshank Redemption.	t	2024-09-13 06:49:08.053873+00	2024-09-13 06:49:08.053873+00	6	24
349	1	Review 349 description for Shazam!.	t	2024-09-13 06:49:08.054877+00	2024-09-13 06:49:08.054877+00	30	4
350	4	Review 350 description for Forrest Gump.	t	2024-09-13 06:49:08.054877+00	2024-09-13 06:49:08.054877+00	8	51
351	2	Review 351 description for The Lion King.	t	2024-09-13 06:49:08.055871+00	2024-09-13 06:49:08.055871+00	22	13
352	4	Review 352 description for Avatar.	t	2024-09-13 06:49:08.055871+00	2024-09-13 06:49:08.055871+00	20	37
353	1	Review 353 description for The Shawshank Redemption.	t	2024-09-13 06:49:08.056872+00	2024-09-13 06:49:08.056872+00	6	14
354	4	Review 354 description for Forrest Gump.	t	2024-09-13 06:49:08.056872+00	2024-09-13 06:49:08.056872+00	8	9
355	3	Review 355 description for The Force Awakens.	t	2024-09-13 06:49:08.057876+00	2024-09-13 06:49:08.057876+00	19	37
356	1	Review 356 description for Batman Begins.	t	2024-09-13 06:49:08.057876+00	2024-09-13 06:49:08.057876+00	29	46
357	3	Review 357 description for Finding Nemo.	t	2024-09-13 06:49:08.058873+00	2024-09-13 06:49:08.058873+00	24	12
358	1	Review 358 description for Star Wars.	t	2024-09-13 06:49:08.058873+00	2024-09-13 06:49:08.058873+00	16	24
359	4	Review 359 description for The Force Awakens.	t	2024-09-13 06:49:08.059872+00	2024-09-13 06:49:08.059872+00	19	20
360	5	Review 360 description for Forrest Gump.	t	2024-09-13 06:49:08.059872+00	2024-09-13 06:49:08.059872+00	8	44
361	2	Review 361 description for Fight Club.	t	2024-09-13 06:49:08.060876+00	2024-09-13 06:49:08.060876+00	7	46
362	3	Review 362 description for The Godfather.	t	2024-09-13 06:49:08.060876+00	2024-09-13 06:49:08.060876+00	9	15
363	2	Review 363 description for The Lion King.	t	2024-09-13 06:49:08.061875+00	2024-09-13 06:49:08.061875+00	22	15
364	5	Review 364 description for The Matrix.	t	2024-09-13 06:49:08.061875+00	2024-09-13 06:49:08.061875+00	1	40
365	4	Review 365 description for Thor.	t	2024-09-13 06:49:08.062873+00	2024-09-13 06:49:08.062873+00	15	46
366	2	Review 366 description for The Hobbit.	t	2024-09-13 06:49:08.062873+00	2024-09-13 06:49:08.062873+00	27	8
367	5	Review 367 description for Jurassic Park.	t	2024-09-13 06:49:08.063881+00	2024-09-13 06:49:08.063881+00	21	3
368	1	Review 368 description for Forrest Gump.	t	2024-09-13 06:49:08.063881+00	2024-09-13 06:49:08.063881+00	8	26
369	1	Review 369 description for The Empire Strikes Back.	t	2024-09-13 06:49:08.064871+00	2024-09-13 06:49:08.064871+00	17	29
370	3	Review 370 description for WALL-E.	t	2024-09-13 06:49:08.065852+00	2024-09-13 06:49:08.065852+00	25	35
371	5	Review 371 description for Return of the Jedi.	t	2024-09-13 06:49:08.065852+00	2024-09-13 06:49:08.065852+00	18	33
372	3	Review 372 description for The Shawshank Redemption.	t	2024-09-13 06:49:08.066872+00	2024-09-13 06:49:08.066872+00	6	11
373	2	Review 373 description for The Dark Knight.	t	2024-09-13 06:49:08.066872+00	2024-09-13 06:49:08.066872+00	4	38
374	5	Review 374 description for Star Wars.	t	2024-09-13 06:49:08.067844+00	2024-09-13 06:49:08.067844+00	16	6
375	2	Review 375 description for Jurassic Park.	t	2024-09-13 06:49:08.067844+00	2024-09-13 06:49:08.067844+00	21	52
376	5	Review 376 description for Spider-Man.	t	2024-09-13 06:49:08.068872+00	2024-09-13 06:49:08.068872+00	13	32
377	1	Review 377 description for Thor.	t	2024-09-13 06:49:08.069858+00	2024-09-13 06:49:08.069858+00	15	47
378	4	Review 378 description for Guardians of the Galaxy.	t	2024-09-13 06:49:08.069858+00	2024-09-13 06:49:08.069858+00	14	21
379	5	Review 379 description for The Matrix.	t	2024-09-13 06:49:08.070873+00	2024-09-13 06:49:08.070873+00	1	19
380	5	Review 380 description for Shazam!.	t	2024-09-13 06:49:08.070873+00	2024-09-13 06:49:08.071883+00	30	13
381	2	Review 381 description for Avatar.	t	2024-09-13 06:49:08.071883+00	2024-09-13 06:49:08.071883+00	20	20
382	4	Review 382 description for Jurassic Park.	t	2024-09-13 06:49:08.071883+00	2024-09-13 06:49:08.071883+00	21	51
383	2	Review 383 description for Guardians of the Galaxy.	t	2024-09-13 06:49:08.072882+00	2024-09-13 06:49:08.072882+00	14	24
384	5	Review 384 description for Fight Club.	t	2024-09-13 06:49:08.072882+00	2024-09-13 06:49:08.072882+00	7	51
385	2	Review 385 description for Thor.	t	2024-09-13 06:49:08.073872+00	2024-09-13 06:49:08.073872+00	15	33
386	4	Review 386 description for Forrest Gump.	t	2024-09-13 06:49:08.073872+00	2024-09-13 06:49:08.073872+00	8	3
387	2	Review 387 description for Guardians of the Galaxy.	t	2024-09-13 06:49:08.073872+00	2024-09-13 06:49:08.074875+00	14	52
388	5	Review 388 description for Toy Story.	t	2024-09-13 06:49:08.074875+00	2024-09-13 06:49:08.074875+00	23	10
389	5	Review 389 description for Forrest Gump.	t	2024-09-13 06:49:08.074875+00	2024-09-13 06:49:08.074875+00	8	15
390	5	Review 390 description for Return of the Jedi.	t	2024-09-13 06:49:08.075872+00	2024-09-13 06:49:08.075872+00	18	30
391	1	Review 391 description for Forrest Gump.	t	2024-09-13 06:49:08.075872+00	2024-09-13 06:49:08.075872+00	8	2
392	1	Review 392 description for Spider-Man.	t	2024-09-13 06:49:08.076872+00	2024-09-13 06:49:08.076872+00	13	40
393	3	Review 393 description for Forrest Gump.	t	2024-09-13 06:49:08.076872+00	2024-09-13 06:49:08.076872+00	8	39
394	2	Review 394 description for Harry Potter.	t	2024-09-13 06:49:08.07787+00	2024-09-13 06:49:08.07787+00	26	51
395	5	Review 395 description for The Avengers.	t	2024-09-13 06:49:08.07787+00	2024-09-13 06:49:08.07787+00	11	2
396	1	Review 396 description for The Dark Knight.	t	2024-09-13 06:49:08.07787+00	2024-09-13 06:49:08.07787+00	4	25
397	2	Review 397 description for The Avengers.	t	2024-09-13 06:49:08.078879+00	2024-09-13 06:49:08.078879+00	11	28
398	4	Review 398 description for Guardians of the Galaxy.	t	2024-09-13 06:49:08.078879+00	2024-09-13 06:49:08.078879+00	14	43
399	4	Review 399 description for Interstellar.	t	2024-09-13 06:49:08.079879+00	2024-09-13 06:49:08.079879+00	3	39
400	4	Review 400 description for Jurassic Park.	t	2024-09-13 06:49:08.079879+00	2024-09-13 06:49:08.079879+00	21	48
\.


--
-- Data for Name: media_app_streamingplatform; Type: TABLE DATA; Schema: public; Owner: nstoykov
--

COPY public.media_app_streamingplatform (id, name, about, website) FROM stdin;
1	Netflix	A streaming service offering a wide variety of TV shows, movies, anime, documentaries, and more.	https://www.netflix.com
2	Hulu	Hulu is a streaming service that offers live TV and on-demand content like TV series and movies.	https://www.hulu.com
3	Amazon Prime Video	Amazon’s video streaming service offers exclusive TV series and movies.	https://www.primevideo.com
4	Disney+	Disney+ offers exclusive movies and TV shows from Disney, Pixar, Marvel, Star Wars, and more.	https://www.disneyplus.com
5	Netflix	A streaming service offering a wide variety of TV shows, movies, anime, documentaries, and more.	https://www.netflix.com
6	Hulu	Hulu is a streaming service that offers live TV and on-demand content like TV series and movies.	https://www.hulu.com
7	Amazon Prime Video	Amazon’s video streaming service offers exclusive TV series and movies.	https://www.primevideo.com
8	Disney+	Disney+ offers exclusive movies and TV shows from Disney, Pixar, Marvel, Star Wars, and more.	https://www.disneyplus.com
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nstoykov
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nstoykov
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nstoykov
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 44, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nstoykov
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nstoykov
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 52, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nstoykov
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nstoykov
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nstoykov
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 11, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nstoykov
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 27, true);


--
-- Name: media_app_media_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nstoykov
--

SELECT pg_catalog.setval('public.media_app_media_id_seq', 30, true);


--
-- Name: media_app_review_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nstoykov
--

SELECT pg_catalog.setval('public.media_app_review_id_seq', 400, true);


--
-- Name: media_app_streamingplatform_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nstoykov
--

SELECT pg_catalog.setval('public.media_app_streamingplatform_id_seq', 8, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: nstoykov
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: nstoykov
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: nstoykov
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: nstoykov
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: nstoykov
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: nstoykov
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: nstoykov
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: nstoykov
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: nstoykov
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: nstoykov
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: nstoykov
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: nstoykov
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: authtoken_token authtoken_token_pkey; Type: CONSTRAINT; Schema: public; Owner: nstoykov
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_pkey PRIMARY KEY (key);


--
-- Name: authtoken_token authtoken_token_user_id_key; Type: CONSTRAINT; Schema: public; Owner: nstoykov
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_key UNIQUE (user_id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: nstoykov
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: nstoykov
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: nstoykov
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: nstoykov
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: nstoykov
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: media_app_media media_app_media_pkey; Type: CONSTRAINT; Schema: public; Owner: nstoykov
--

ALTER TABLE ONLY public.media_app_media
    ADD CONSTRAINT media_app_media_pkey PRIMARY KEY (id);


--
-- Name: media_app_review media_app_review_pkey; Type: CONSTRAINT; Schema: public; Owner: nstoykov
--

ALTER TABLE ONLY public.media_app_review
    ADD CONSTRAINT media_app_review_pkey PRIMARY KEY (id);


--
-- Name: media_app_streamingplatform media_app_streamingplatform_pkey; Type: CONSTRAINT; Schema: public; Owner: nstoykov
--

ALTER TABLE ONLY public.media_app_streamingplatform
    ADD CONSTRAINT media_app_streamingplatform_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: nstoykov
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: nstoykov
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: nstoykov
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: nstoykov
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: nstoykov
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: nstoykov
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: nstoykov
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: nstoykov
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: nstoykov
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: authtoken_token_key_10f0b77e_like; Type: INDEX; Schema: public; Owner: nstoykov
--

CREATE INDEX authtoken_token_key_10f0b77e_like ON public.authtoken_token USING btree (key varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: nstoykov
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: nstoykov
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: nstoykov
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: nstoykov
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: media_app_media_streaming_platform_id_c6429b8e; Type: INDEX; Schema: public; Owner: nstoykov
--

CREATE INDEX media_app_media_streaming_platform_id_c6429b8e ON public.media_app_media USING btree (streaming_platform_id);


--
-- Name: media_app_review_media_id_7ce0546e; Type: INDEX; Schema: public; Owner: nstoykov
--

CREATE INDEX media_app_review_media_id_7ce0546e ON public.media_app_review USING btree (media_id);


--
-- Name: media_app_review_reviewer_id_5d9013a6; Type: INDEX; Schema: public; Owner: nstoykov
--

CREATE INDEX media_app_review_reviewer_id_5d9013a6 ON public.media_app_review USING btree (reviewer_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: nstoykov
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: nstoykov
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: nstoykov
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: nstoykov
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: nstoykov
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: nstoykov
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: nstoykov
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authtoken_token authtoken_token_user_id_35299eff_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: nstoykov
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_35299eff_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: nstoykov
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: nstoykov
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: media_app_media media_app_media_streaming_platform_i_c6429b8e_fk_media_app; Type: FK CONSTRAINT; Schema: public; Owner: nstoykov
--

ALTER TABLE ONLY public.media_app_media
    ADD CONSTRAINT media_app_media_streaming_platform_i_c6429b8e_fk_media_app FOREIGN KEY (streaming_platform_id) REFERENCES public.media_app_streamingplatform(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: media_app_review media_app_review_media_id_7ce0546e_fk_media_app_media_id; Type: FK CONSTRAINT; Schema: public; Owner: nstoykov
--

ALTER TABLE ONLY public.media_app_review
    ADD CONSTRAINT media_app_review_media_id_7ce0546e_fk_media_app_media_id FOREIGN KEY (media_id) REFERENCES public.media_app_media(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: media_app_review media_app_review_reviewer_id_5d9013a6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: nstoykov
--

ALTER TABLE ONLY public.media_app_review
    ADD CONSTRAINT media_app_review_reviewer_id_5d9013a6_fk_auth_user_id FOREIGN KEY (reviewer_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: DATABASE cinebase; Type: ACL; Schema: -; Owner: postgres
--

GRANT ALL ON DATABASE cinebase TO nstoykov;


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT ALL ON SCHEMA public TO nstoykov;


--
-- PostgreSQL database dump complete
--

--
-- Database "postgres" dump
--

\connect postgres

--
-- PostgreSQL database dump
--

-- Dumped from database version 17rc1
-- Dumped by pg_dump version 17rc1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- PostgreSQL database dump complete
--

--
-- PostgreSQL database cluster dump complete
--

