# Generated by Django 5.1 on 2024-09-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
