# Generated by Django 5.1 on 2024-09-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0003_remove_media_number_rating_alter_media_avg_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='avg_rating',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
    ]
