# Generated by Django 5.1 on 2024-09-13 06:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0004_alter_media_avg_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='user_rating',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='media',
            name='avg_rating',
            field=models.FloatField(default=0, null=True),
        ),
    ]
